esphome:
  name: ${device_name}

web_server:
  port: 80
  version: 1

logger:

ota:
  password: "123"

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true

  ap:
    ssid: "ESPHome ${device_name} hotspot"
    password: ${hotspot_password}

captive_portal:

mqtt:
  id: mqtt_client
  discovery: false
  broker: ${mqtt_broker}
  on_json_message:
    - topic: temperature/command/rename
      then:
        lambda: |-
          const char* address;
          const char* name;
          id(sensor_names).clear();
          for (JsonObjectConst::iterator it = x.begin(); it != x.end(); ++it) {
            address = it->key().c_str();
            name = it->value().as<const char*>();
            id(sensor_names)[address] = name;
            ESP_LOGW("rename", "Renamed sensor with address %s to %s", address, name);     
          }
