substitutions:
  device_name: "skambaliukas"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  common: github://w4zZz4p/automation/packages/common.yaml@master
  wifi-signal: github://w4zZz4p/automation/packages/wifi-signal.yaml@master


esp8266:
  board: nodemcuv2

binary_sensor:
  - platform: gpio
    pin:
      number: D3
      inverted: true
    name: "Test button"
