sensor:
  - platform: wifi_signal
    name: "${device_name} WIFI signal"
    update_interval: 15s

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${device_name} SSID"
    ip_address:
      name: "${device_name} IP address"
    mac_address:
      name: "${device_name} MAC address"
