esphome:
  name: ${device_name}

web_server:
  port: 80
  version: 1

logger:

ota:
  password: "123"

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true

  ap:
    ssid: "ESPHome ${device_name} hotspot"
    password: ${hotspot_password}

captive_portal:

mqtt:
  id: mqtt_client
  discovery: false
  broker: "broker.hivemq.com"
