substitutions:
  device_name: "door-bell"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  hotspot_password: !secret hotspot_password
  mqtt_broker: "broker.hivemq.com"

packages:
  common: !include packages/common.yaml
  sensor-wifi-signal: !include packages/sensors/wifi-data.yaml

esp8266:
  board: nodemcuv2

uart:
  tx_pin: D4
  rx_pin: D1
  baud_rate: 9600

dfplayer:

mqtt:
  on_message:
    topic: my/custom/topic
    qos: 0
    then:
      if:
        condition:
          not: dfplayer.is_playing
        then:
          dfplayer.play: !lambda 'return std::stoi(x);'


script:
  id: actionSkambutis
  then:
    if:
      condition:
        not: dfplayer.is_playing
      then:
        dfplayer.play: 1

button:
  platform: template
  name: "Skambutis"
  on_press:
    script.execute: actionSkambutis


binary_sensor:
  platform: gpio
  pin: D3
  name: "test button"
  filters:
    invert:
  on_press:
    then:
      script.execute: actionSkambutis

logger:
  level: VERBOSE
