substitutions:
  device_name: "temperature"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  hotspot_password: !secret hotspot_password

packages:
  common: !include { file: common/common.yaml }
  wifi-data: !include { file: common/sensors/wifi-data.yaml }
  ds18b20-0: !include { file: temperature/ds18b20.yaml, vars: { index: 0 } }
  ds18b20-1: !include { file: temperature/ds18b20.yaml, vars: { index: 1 } }
  ds18b20-2: !include { file: temperature/ds18b20.yaml, vars: { index: 2 } }
  ds18b20-3: !include { file: temperature/ds18b20.yaml, vars: { index: 3 } }
  ds18b20-4: !include { file: temperature/ds18b20.yaml, vars: { index: 4 } }
  ds18b20-5: !include { file: temperature/ds18b20.yaml, vars: { index: 5 } }
  ds18b20-6: !include { file: temperature/ds18b20.yaml, vars: { index: 6 } }
  ds18b20-7: !include { file: temperature/ds18b20.yaml, vars: { index: 7 } }
  ds18b20-8: !include { file: temperature/ds18b20.yaml, vars: { index: 8 } }
  ds18b20-9: !include { file: temperature/ds18b20.yaml, vars: { index: 9 } }

esp8266:
  board: nodemcuv2

esphome:
  includes:
    - temperature/temperature.h

mqtt:
  on_json_message:
    - topic: temperature/command/rename
      then:
        lambda: temperature::handle_json(x);

dallas:
  - pin: D0
    update_interval: 10s
