esphome:
  name: ${device_name}

web_server:
  port: 80

logger:

ota:
  password: ""

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: "${device_name} hotspot"
    password: ${hotspot_password}

captive_portal:

mqtt:
  broker: ${mqtt_broker}
